### ISSUE TITLE
Add support for implementing a JSON-RPC proxy

### ISSUE THREAD

**Issue by kdeme** [status-im/nim-json-rpc#102]
Add support for implementing a JSON-RPC proxy that can filter and forward specific methods from an API to another end-point.

This would be directly useful in the `nlpn` project. 
See also issue https://github.com/status-im/nimbus-eth1/issues/723

Example in Go of such proxy: https://github.com/gochain/rpc-proxy

Part of this task is basically investigating what the best way is to add such functionality.

**Comment by jangko** [comment]
fixed by #105, closing.
