### ISSUE TITLE
Robustness

### ISSUE THREAD

**Issue by coffeepots** [status-im/nim-json-rpc#17]
- [x] Server errors reported correctly via async messages
- [x] Server using proper logging library
- [x] Handling of large data lines
  - [x] Hard limit or stream processing
- [ ] Improve error checking tests
  - [ ] Malformed json (currently hangs client)
    - [ ] Loses `id` field, messes up next response, cannot sync future calls
  - [ ] Incorrect data input such as non-hex values
  - [ ] Handling of exceptions within rpc body

**Comment by jangko** [comment]
fixed by #178, closing
