### ISSUE TITLE
Tagged versions?

### ISSUE THREAD

**Issue by emizzle** [status-im/nim-json-rpc#208]
According to the [nimble docs](https://github.com/nim-lang/nimble#nimble-install), versions must be tagged for nimble install to work correctly:

> Nimble always fetches and installs the latest version of a package. Note that the latest version is defined as the latest tagged version in the Git (or Mercurial) repository, if the package has no tagged versions then the latest commit in the remote repository will be installed. If you already have that version installed, Nimble will ask you whether you wish to overwrite your local copy.

**Comment by AuHau** [comment]
Latest release was tagged: https://github.com/status-im/nim-json-rpc/releases/tag/v0.5.0 so can be closed.
