### ISSUE TITLE
Remove dependency on Ethereum components

### ISSUE THREAD

**Issue by coffeepots** [status-im/nim-json-rpc#28]
If this is to become a generic use case RPC library, the Ethereum related tests that pull in `stint` and `nimcrypto` should be moved somewhere else, either to Nimbus or as a separate project.

Most RPC users are unlikely to need these libraries.

**Comment by zah** [comment]
All references to Ethereum now exist only in the tests folder which is considered an adequate solution. We can consider moving them to the test suite of `nim-web3` in the future.
