### ISSUE TITLE
httpclient doesn't support chunked transfer encoding when receiving response

### ISSUE THREAD

**Issue by jangko** [status-im/nim-json-rpc#36]
for example, parity ethereum client uses `Transfer-Encoding: chunked` and no `Content-Length` field.
this make httpclient unusable to perform rpc

**Comment by jangko** [comment]
both geth and parity, rpc method `eth_getTransactionByHash`
`0x5c4fdc85bf5efdfcbf7d4991c37287a9c3d5b660b57b0082118c3cff3c69dff1`
return this kind of response.

how to check it with curl:

```text
curl -H "Content-Type:application/json" --data '{"jsonrpc":"2.0","method":"eth_getTransactionByHash","params":["0x5c4fdc85bf5efdfcbf7d4991c37287a9c3d5b660b57b0082118c3cff3c69dff1"],"id":1}" localhost:8545 -v
```

**Comment by jangko** [comment]
this feature now supported by chronos HTTP, we only need to switch to chronos HTTP server

**Comment by orangeagain** [comment]
How to disable transfer-encoding ?
