### ISSUE TITLE
httpserver need to implement CORS(Cross Origin Resource Sharing) policy

### ISSUE THREAD

**Issue by jangko** [status-im/nim-json-rpc#38]
supposed the server is queried by a browser or by a debugging tool running inside a browser, enabling CORS will be handy.

link: [how to make cross domain request](https://www.moxio.com/blog/12/how-to-make-a-cross-domain-request-in-javascript-using-cors)

**Comment by coffeepots** [comment]
Sorry not sure how/why this was closed!
