### ISSUE TITLE
Review notes about news package.

### ISSUE THREAD

**Issue by cheatfate** [status-im/nim-json-rpc#62]
Like a month ago, **news** package https://github.com/tormund/news was added as dependency for `nim-json-rpc`. This package is Websocket implementation.

1. Package repository missing CI tests, also the only test present is absolutely trivial.
2. Package using `oids` to generate random security key.
3. Package using `securehash` (which is SHA-1) to generate security key. First of all because stdlib's securehash do not have tests.
4. Package using stdlib's `random` which is not CSPRNG.
5. Package using `base64 encoding from stdlib (which is also missing tests).
6. Usage of `sleepAsync(1)` hacks.

**Comment by Swader** [comment]
@yglukhov this might affect things, no?

**Comment by cheatfate** [comment]
7. Also want to add that during handshake client is advertising support of **deflate** compression `Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits`, but there actually no compression/decompression code.
