### ISSUE TITLE
[Nim 0.20.x] httpclient call is not GC-safe

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-json-rpc#63]
FYI, I was on devel by mistake and add a not gcsafe error for this method: https://github.com/status-im/nim-json-rpc/blob/af33cb9fbc3993247bbf899abb03f8a84c1d7d82/json_rpc/clients/httpclient.nim#L174-L175

No compilation problem on 0.19.6

**Comment by jangko** [comment]
fixed by #178, closing
