### ISSUE TITLE
Example in README doesn't work

### ISSUE THREAD

**Issue by iffy** [status-im/nim-json-rpc#67]
When I run this:

```nim
import json_rpc/rpcserver

var router = newRpcRouter()

router.rpc:
  result = %"Hello"
```

I get this:

```
/private/tmp/goo.nim(6, 3) Error: undeclared identifier: 'result'
```

Am I doing something wrong?  I installed with `nimble install json_rpc`

**Comment by larkwiot** [comment]
Neither does the Server example. Apparently this project is abandoned
