### ISSUE TITLE
Add websocket server support

### ISSUE THREAD

**Issue by kdeme** [status-im/nim-json-rpc#76]
There is already websocket client support through the news package: https://github.com/status-im/nim-json-rpc/blob/master/json_rpc/clients/websocketclient.nim

Could do similar for the server side with [news](https://github.com/Tormund/news).
But in the examples there `asynchttpserver` is used. So, we would have to do something similar but adjust it so that is uses the the httpserver of nim-json-rpc.

**Comment by geohuz** [comment]
It's the exact feature I'm currently looking, thanks!

**Comment by kdeme** [comment]
So it looks like this would require upstream changes to the news package also, as `newWebsocket` for the server side requires the `Request` object as parameter, and is also put behind a flag as it is not available for usage with chronos: https://github.com/Tormund/news/blob/master/src/news.nim#L115
