### ISSUE TITLE
WebSocketClient to receive the message forever.

### ISSUE THREAD

**Issue by geohuz** [status-im/nim-json-rpc#77]
I'm not sure how to implement a client "subscribe" to the server and receive message from server forever, currently if I use 

```
let response = waitFor client.call("add", params)
```
I only get the first response from server, but the scenario is when server accept the subscription then client should receive message from server consequently(streaming data)

**Comment by jangko** [comment]
this is actually a good feature to implement. see https://geth.ethereum.org/docs/rpc/pubsub

nim-websock have this ability but currently the websocket session in nim-json-rpc is hidden from the rpc method and also hidden from the app using this server.

exposing all active sessions to the app is easy, but telling the rpc method which ws session is active at the time of the rpc-method execution is a bit tricky. but issue #128 also reveals the possibility to use `hidden/magic` `param/variable` to pass the current session without breaking existing rpc method implementation.

**Comment by jangko** [comment]
This is now supported via `onProcessMessage` hook implemented in #186.
see nim-web3 how subscription works. closing.
