### ISSUE TITLE
Handle omitted params

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-json-rpc#93]
From discussion with RocketPool:

https://discord.com/channels/613988663034118151/616299964242460682/807667789619134495

> So long story short, here's what I'm seeing:
> ![image](https://user-images.githubusercontent.com/22738317/107125682-af9e1000-68ab-11eb-915f-0e98a060c622.png)
> I have to explain so let me give you some context
> On the left is a sample of what curl sends using the API examples you provide in https://nimbus.guide/api.html for, as an example, get_v1_node_syncing: `curl -d '{"jsonrpc":"2.0","method":"get_v1_node_syncing","params":[],"id":1}' -H 'Content-Type: application/json' localhost:9190 -s | jq`
>
> On the right is what RP's stack is producing, which is resulting in no response from Nimbus - the problem is that all of the Go libraries for json-rpc I've used so far will omit the params key when it's empty
> Example: https://github.com/ethereum/go-ethereum/blob/e7872729012a4871397307b12cc3f4772ffcbec6/rpc/json.go#L55
> Exmaple 2: https://github.com/powerman/rpc-codec/blob/6f3efa778da423a2df7f44881f5617ae8fff3e84/jsonrpc2/client.go#L50
> But in nim-json-rpc, as far as I can tell, you throw an error when the params field isn't present - see https://github.com/status-im/nim-json-rpc/blob/99455437ba3d83d5af1c38007fedeeff295e959e/json_rpc/router.nim#L39

**Comment by mratsim** [comment]
Ping jcrtp on discord once solved

**Comment by jclapis** [comment]
Hi, jcrtp here. Here's what [the official JSON-RPC 2.0 spec](https://www.jsonrpc.org/specification#parameter_structures) has to say about this:

> 4 Request object
> 
> A rpc call is represented by sending a Request object to a Server. The Request object has the following members:
>
>... 
>params
>    A Structured value that holds the parameter values to be used during the invocation of the method. This member MAY be omitted.
>...

It looks like these Go libraries are taking advantage of the "MAY be omitted" clause, so their behavior should be considered legal.
